name: Run tests
on:
  push:
    branches:
<<<<<<< HEAD
      - 'main'      
=======
      - 'main'
  pull_request:
    branches:
      - 'main'
>>>>>>> c5b91cf2080e53bf668efaaf0d8399fbddc81067
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: [16.x,18.x]
      
      - name: Install Dependencies
        run: npm install
  
      - name: run tests
        run: npm test
